# Louvre 

Source: https://de.wikipedia.org/wiki/Louvre

Der Ursprung der Sammlung geht auf das 14. Jahrhundert zurück. Der Herzog Jean de Berry (1340–1415), ein Bruder Karls V., legte eine Sammlung von Gemälden, Tapisserien und Buchmalereien an, von denen einige noch in der heutigen Ausstellung zu sehen sind.
Mona Lisa (Leonardo da Vinci, 1503–1505)

Der eigentliche Begründer der Sammlung ist aber König Franz I. (1515–1547), der als der erste große Sammler und Mäzen auf Frankreichs Thron gilt. Er richtete auch dem greisen Leonardo da Vinci 1517 ein Domizil an der Loire ein. Nach Leonardos Tod 1519 gelangten dessen Bilder – darunter wahrscheinlich auch die Mona Lisa – in die Sammlung des Königs, die zu dieser Zeit noch im Schloss Fontainebleau aufbewahrt wurde.

Kardinal Richelieu, der 1624 Minister unter Ludwig XIII. wurde, baute auf Staatskosten eine große Privatsammlung auf, die 1636 zum Großteil in den Besitz der Krone überging. 1660 zog die Sammlung in den Louvre um. Auch unter Ludwig XIV. wurden kostbare Werke erworben, unter anderem von Tizian und Raffael.
Öffnung für das Publikum

Unter Ludwig XV. wurden kaum noch neue Bilder der Sammlung hinzugefügt. Dass die Sammlung der Öffentlichkeit nicht zugänglich war, führte zu allgemeiner Kritik, worauf 1750 im Palais du Luxembourg die erste Gemäldegalerie Frankreichs eröffnet wurde. Bereits 1779 wurde sie jedoch wieder geschlossen, da das Palais als Wohnung des späteren Ludwig XVIII. dienen sollte. Die Bilder wurden zurück ins Depot des Louvre gebracht. Der Politiker Charles Claude Flahaut de La Billarderie plante die Schaffung eines französischen Nationalmuseums.

Im Zuge der Französischen Revolution wurde die Sammlung mit Dekret der Nationalversammlung vom 27. Juli 1793 zum ersten Mal im Louvre zugänglich gemacht. Am 10. August 1793, auf den Tag genau ein Jahr nach Abschaffung der Monarchie, wurde sie als Zentrales Kunstmuseum der Republik eröffnet.
Weiterer Ausbau

Napoleon Bonaparte erteilte nach dem siegreichen Italienfeldzug den ausdrücklichen Befehl, berühmte Kunstwerke im Ausland für Frankreich zu requirieren. Bald schon konnte der Louvre die Kunstwerke aus Rom, Venedig, Berlin, Wien und vielen anderen europäischen Städten nicht mehr fassen. Unter Napoleon I. entstanden im Rahmen seines groß angelegten, bahnbrechenden nationalen Kultur-Programms 15 Zweigmuseen in ganz Frankreich, in denen Bilder der Sammlung zum ersten Mal einer breiten Öffentlichkeit in der französischen Provinz zugänglich waren. Nach dem Fall des Kaiserreichs im Jahre 1814 wurde der zukunftsweisende volkspädagogische Ansatz Napoleons I. nicht mehr weiterverfolgt; die Beutekunst wurde von den Alliierten wieder aus dem Louvre zurückgeholt, wodurch das nationale Element der Sammlung wieder in den Vordergrund trat.

1821 wurde mit dem Ankauf der Venus von Milo der Aufbau der Antikensammlung fortgesetzt. Seit 1808 war bereits die Antikensammlung der Borghese Teil der Sammlung. 1826 folgten die ägyptische und 1847 die assyrische Abteilung. Ab 1851 wurde die Ausstellungsfläche des Louvre unter Alfred Émilien de Nieuwerkerke erweitert. Nach dem Sturz des zweiten Kaiserreichs 1870 wurde die Sammlung endgültig von der Krone getrennt und verstaatlicht.

Der Sammlung kam zugute, dass seit 1972 die Erbschaftsteuer auch in Form von Kunstwerken entrichtet werden kann.
Grand-Louvre und heutiger Zustand

Staatspräsident François Mitterrand initiierte 1981 das Projekt „Grand-Louvre“, mit dem der gesamte Gebäudekomplex einer musealen Nutzung unterworfen wurde; 1999 wurde es abgeschlossen. Das Finanzministerium zog um;[2] in diesem Rahmen wurde unter anderem die Galerie d’Apollon restauriert und die Glaspyramide im Innenhof des Louvre geschaffen. Die Glaspyramide wurde von Ieoh Ming Pei entworfen und 1989 eröffnet. Sie dient heute als Haupteingang zum Musée du Louvre. Anfangs als „Gewächshaus“ und „Käseglocke“ verspottet, ist die Pyramide heute zu einem bekannten Wahrzeichen von Paris geworden.